name: project  
channels:
  - defaults  
  - conda-forge  

dependencies:
  - python=3.9  
  - numpy=1.21.*  
  - pandas=1.3.*  
  - matplotlib=3.4.*  
  - seaborn=0.11.*  
  - jupyterlab  

  
  - pytorch=1.12.*  
  - torchvision=0.13.*  

  
  - scikit-learn=0.24.*  
  - scikit-image=0.18.*  
  - tqdm  
  - pip  

  # Optional: list any additional packages required for your project
  - pip:
      - transformers==4.12.*  # For NLP tasks (optional)
      - fastai==2.5.*  # High-level library for deep learning (optional)

# Optional: Include any other relevant details
