name: CSE543-AI
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch=2.4.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tensorflow