name: project  
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - numpy=1.26.0
  - pandas=2.1.1
  - matplotlib=3.8.0
  - scikit-learn=1.3.0
  - jupyterlab=4.0.5
  - pytest=7.4.2
  - black=23.9.1
  - flake8=6.1.0
  - pip